import os
import json
import random


def get_image_names(directory):
    items = []
    eye_values = ["big", "small", "yellow", "blue"]
    ear_values = ["pointed", "droopy"]
    face_values = ["serious", "surprised", "calm", "excited"]
    shirt_values = ["fancy", "casual"]
    background_values = ["moon", "broken"]
    color_values = ["red", "black"]
    counter = 1
    descriptions_values = [
        "A stealthy feline with extraordinary ninja skills.",
        "Mysterious and graceful, this cat prowls the night.",
        "Inspired by the moon, this cat is a master of disguise.",
        "Quick and agile, this cat moves like a shadow in the darkness.",
        "A nocturnal warrior with eyes that gleam like the moon.",
        "An artist of stealth and precision, this cat paints the night with elegance.",
        "A ninja cat that wields watercolor brushes with skill and finesse.",
        "This cat's ninja prowess is matched only by its love for the moon.",
        "A master of acrobatics and stealth, this cat roams the night fearlessly.",
        "With the grace of a moonlit dancer, this cat leaves its mark on the world.",
        "A mysterious feline with captivating moonlit eyes.",
        "The shadows whisper tales of this cat's silent prowess.",
        "In the cover of darkness, this cat becomes one with the night.",
        "Eyes like glowing orbs, this cat navigates the moonlit landscape.",
        "With each stroke of its paw, this cat paints the world in moonlight.",
        "A master of the brush and the blade, this cat embraces both art and combat.",
        "Moonlight dances upon this cat's sleek fur, revealing its hidden powers.",
        "A moonstruck warrior with a heart as vast as the night sky.",
        "In the realm of shadows, this cat reigns supreme with its ninja skills.",
        "With each leap and bound, this cat becomes a ghost in the moonlight.",
        "A whiskered artist creating masterpieces with the subtle strokes of watercolor.",
        "The moon's enchantment flows through this cat's veins, igniting its ninja spirit.",
        "A fearless acrobat, this cat moves with grace and precision under the moon's gaze.",
        "With eyes that shine like silver, this cat embodies the mystique of the night.",
        "A guardian of the moon, this cat protects its secrets with unwavering devotion.",
        "Silent as a whisper, this cat blends into the moonlit tapestry of the night.",
        "With a swift flick of its tail, this cat conjures moonlit magic.",
        "A nocturnal wanderer, this cat explores the world under the moon's gentle glow.",
        "Eyes aglow with moonlit fire, this cat is a force to be reckoned with.",
        "Stealthy and mysterious, this cat prowls the shadows with silent determination.",
        "In the moon's embrace, this cat finds its true strength and purpose.",
        "A nimble warrior with a heart as wild as the night sky.",
        "A master of camouflage, this cat disappears into the moonlit scenery.",
        "Eyes shining with lunar wisdom, this cat is a beacon of moonlight in the dark.",
        "With each step, this cat leaves a trail of stardust in its wake.",
        "A moonlit sentinel, this cat keeps a watchful eye over the world.",
        "A shadowy figure blending seamlessly into the night, this cat is a true ninja.",
        "Whiskers quivering with anticipation, this cat is ready to unleash its moonlit powers.",
        "With the grace of a moonbeam, this cat dances through the night.",
        "A nocturnal painter, this cat brings the night to life on its canvas.",
        "In the moon's reflection, this cat finds its true self.",
        "A celestial warrior, this cat harnesses the power of the moon for its battles.",
        "Eyes like shimmering moonstones, this cat is a rare and precious gem.",
        "Silent as moonlight, this cat moves with grace and precision.",
        "A nocturnal hunter with a taste for moonlit adventures.",
        "A true ninja of the night, this cat's skills are unmatched.",
        "With a flick of its tail, this cat conjures moonlit dreams.",
        "A cunning warrior with eyes that reflect the depths of the night sky.",
        "A moonlit muse, this cat inspires creativity with every brushstroke.",
        "Eyes like sparkling galaxies, this cat holds the mysteries of the universe.",
        "A guardian of the night, this cat's presence brings solace under the moon's watchful eye.",
        "In the moon's glow, this cat becomes an ethereal beauty.",
        "A nimble acrobat, this cat dances across rooftops under the moon's approving gaze.",
        "With each stroke of its paw, this cat weaves moonlight into art.",
        "A master of disguise, this cat blends seamlessly into the moonlit landscape.",
        "Eyes that shine with the brilliance of a thousand stars, this cat is truly celestial.",
        "In the depths of darkness, this cat's spirit shines like a guiding moonbeam.",
        "A shadowy figure cloaked in mystery, this cat is a true enigma of the night.",
        "With a twinkle in its eye, this cat reveals the secrets of the moon.",
        "A night-time adventurer, this cat explores the world when others slumber.",
        "Eyes that hold the wisdom of countless moonlit nights, this cat is an old soul.",
        "With the moon as its guide, this cat fearlessly navigates the darkness.",
        "A mysterious wanderer, this cat follows the moon's path on its nocturnal quests.",
        "A brush-wielding ninja, this cat creates masterpieces under the moon's gentle glow.",
        "With each moonrise, this cat's powers awaken to protect the night.",
        "A moonlit guardian, this cat watches over slumbering souls with unwavering devotion.",
        "In the moon's embrace, this cat finds solace and strength.",
        "A graceful dancer in the moonlight, this cat moves with effortless beauty.",
        "Eyes filled with moonlit secrets, this cat holds the key to hidden realms.",
        "A phantom of the night, this cat moves undetected under the moon's silver light.",
        "With a sprinkle of stardust, this cat brings magic to the world.",
        "A creature of the night, this cat roams freely under the moon's gentle glow.",
        "Eyes like shimmering pools of moonlight, this cat captivates all who gaze upon it.",
        "A moonlit spirit, this cat's presence brings calm to chaotic nights.",
        "A shadow dancer, this cat moves with grace and fluidity under the moon's watchful eye.",
        "With a moonbeam in its step, this cat treads lightly on the world.",
        "A twilight prowler, this cat emerges as dusk settles and the moon rises.",
        "Eyes that reflect the mysteries of the cosmos, this cat is a window to the universe.",
        "A moonlit warrior with a heart as fierce as the night sky.",
        "In the moon's glow, this cat reveals its true nature - a fearless ninja.",
        "A master of illusion, this cat plays tricks with moonlight and shadow.",
        "With each stroke of its brush, this cat paints the world in shades of moonlit beauty.",
        "A moonstruck artist, this cat channels the night's energy into its creations.",
        "A ninja of the moon, this cat strikes fear into the hearts of its enemies.",
        "Eyes like silver moons, this cat sees through the darkness with clarity.",
        "A lunar muse, this cat inspires dreams and imagination.",
        "With the moon as its guide, this cat embarks on nocturnal adventures.",
        "A creature of the twilight, this cat thrives in the enchanting hours of the night.",
        "Eyes that shimmer like moonlit waters, this cat is a reflection of tranquility.",
        "A shadow warrior, this cat fights battles unseen under the moon's protective veil.",
        "In the moon's embrace, this cat finds peace and serenity.",
        "A moonlit wanderer, this cat roams the world in search of hidden treasures.",
        "A phantom presence, this cat leaves no trace as it moves through the night.",
        "With a twinkle in its eye, this cat reveals the magic of the moonlit world.",
        "A nocturnal enchanter, this cat weaves spells under the moon's enchanting glow.",
        "Eyes that hold the wisdom of ancient moonlit rituals, this cat is a wise sage.",
        "A moonlit sentinel, this cat guards the night with unwavering vigilance.",
        "In the moon's radiance, this cat becomes a beacon of hope and guidance.",
        "A shadowy silhouette against the moon, this cat is a symbol of mystery and intrigue.",
        "With each leap, this cat defies gravity and dances with the moon.",
        "A nocturnal maestro, this cat conducts symphonies of moonlit melodies.",
        "Eyes that flicker like distant stars, this cat is a celestial being.",
        "A lunar warrior, this cat fights for justice under the moon's guiding light.",
        "In the moon's glow, this cat's true colors shine brightly.",
        "A creature of the night, this cat harnesses the power of the moon for its endeavors.",
        "With a graceful paw, this cat paints the night sky with shimmering watercolors.",
        "A moonlit guardian, this cat protects the world from the shadows that lurk.",
        "A ghostly figure in the moonlight, this cat haunts the dreams of its adversaries.",
        "Eyes that hold the secrets of the universe, this cat is a cosmic oracle.",
        "A twilight dancer, this cat moves with elegance and grace under the moon's gentle gaze.",
        "With each moonbeam, this cat absorbs the moon's energy and becomes stronger.",
        "A night-time explorer, this cat embarks on adventures that unfold under the moon's light.",
        "Eyes that gleam with the fire of a thousand suns, this cat is a celestial marvel.",
        "A moonlit sage, this cat imparts wisdom and guidance to those who seek it.",
        "In the moon's reflection, this cat finds serenity and inner peace.",
        "A mysterious shadow, this cat blends seamlessly into the night's canvas.",
        "With a whisker twitch, this cat commands the forces of the moon and the night.",
        "A twilight wanderer, this cat ventures into the unknown as the world sleeps.",
        "Eyes like shimmering constellations, this cat holds the map to the cosmos.",
        "A moonlit warrior, this cat fights battles with a ferocity fueled by lunar energy.",
        "In the moon's embrace, this cat finds solace and comfort.",
        "A phantom of the darkness, this cat leaves no trace as it navigates the night.",
        "With a moonlit aura, this cat emanates an otherworldly presence.",
        "A nocturnal dancer, this cat moves with elegance and grace under the moon's silver light.",
        "Eyes that twinkle with the magic of the moon, this cat enchants all who cross its path.",
        "A moonlit guardian, this cat keeps watch over the secrets of the night.",
        "A mysterious silhouette against the moon, this cat is a symbol of beauty and mystery.",
        "With each leap, this cat defies gravity and soars through the moonlit sky.",
        "A conductor of the night, this cat orchestrates symphonies of moonlit wonder.",
        "Eyes that hold the wisdom of ancient celestial beings, this cat is a timeless soul.",
        "A moonlit sentinel, this cat stands vigilant in the face of darkness.",
        "In the moon's radiance, this cat becomes a beacon of hope and tranquility.",
        "A shadowy figure shrouded in mystery, this cat is a enigma of the night.",
        "With each flick of its tail, this cat weaves moonlight into spells of enchantment.",
        "A nocturnal adventurer, this cat explores hidden realms under the moon's gentle glow.",
        "Eyes that sparkle like distant galaxies, this cat is a cosmic marvel.",
        "A lunar guardian, this cat protects the world from the terrors of the night.",
        "In the moon's glow, this cat's true nature is revealed - a fearless warrior.",
        "A master of shadows, this cat moves undetected under the moon's watchful eye.",
        "With a gentle touch, this cat paints the world in shades of moonlit wonder.",
        "A moonstruck visionary, this cat sees beyond the boundaries of the mortal world.",
        "A moonlit sentinel, this cat keeps the night safe from harm.",
        "A ghostly figure drifting through the moonlight, this cat is a mysterious presence.",
        "Eyes that hold the secrets of the cosmos, this cat is a cosmic oracle.",
        "A twilight dancer, this cat moves with grace and elegance under the moon's tender gaze.",
        "With each moonbeam, this cat absorbs the moon's energy and grows stronger.",
        "A night-time explorer, this cat embarks on journeys that unfold under the moon's light.",
        "Eyes that shimmer like distant stars, this cat is a celestial wonder.",
        "A moonlit sage, this cat imparts wisdom and guidance to those who seek it.",
        "In the moon's reflection, this cat finds serenity and inner peace.",
        "A mysterious shadow, this cat melds seamlessly into the night's tapestry.",
        "With a whisker twitch, this cat commands the forces of the moon and the night.",
        "A twilight wanderer, this cat ventures into the unknown while the world sleeps.",
        "Eyes like shimmering constellations, this cat holds the map to the cosmos.",
        "A moonlit warrior, this cat fights with a ferocity fueled by lunar energy.",
        "In the moon's embrace, this cat finds solace and comfort.",
        "A phantom of the darkness, this cat leaves no trace as it navigates the night.",
        "With a moonlit aura, this cat emanates an otherworldly presence.",
        "A nocturnal dancer, this cat moves with elegance and grace under the moon's silver light.",
        "Eyes that twinkle with the magic of the moon, this cat enchants all who cross its path.",
        "A moonlit guardian, this cat keeps watch over the secrets of the night.",
        "A mysterious silhouette against the moon, this cat is a symbol of beauty and mystery.",
        "With each leap, this cat defies gravity and soars through the moonlit sky.",
        "A conductor of the night, this cat orchestrates symphonies of moonlit wonder.",
        "Eyes that hold the wisdom of ancient celestial beings, this cat is a timeless soul.",
        "A moonlit sentinel, this cat stands vigilant in the face of darkness.",
        "In the moon's radiance, this cat becomes a beacon of hope and tranquility.",
        "A shadowy figure shrouded in mystery, this cat is an enigma of the night.",
        "With each flick of its tail, this cat weaves moonlight into spells of enchantment.",
        "A nocturnal adventurer, this cat explores hidden realms under the moon's gentle glow.",
        "Eyes that sparkle like distant galaxies, this cat is a cosmic marvel.",
        "A lunar guardian, this cat protects the world from the terrors of the night.",
        "In the moon's glow, this cat's true nature is revealed - a fearless warrior.",
        "A master of shadows, this cat moves undetected under the moon's watchful eye.",
        "With a gentle touch, this cat paints the world in shades of moonlit wonder.",
        "A moonstruck visionary, this cat sees beyond the boundaries of the mortal world.",
        "A guardian of the night, this cat wards off the darkness with unwavering resolve.",
        "Eyes that hold the mysteries of the universe, this cat is a celestial enigma.",
        "A twilight dancer, this cat's movements are a graceful ballet in the moonlight.",
        "With each moonbeam, this cat's powers of transformation grow stronger.",
        "A seeker of nocturnal treasures, this cat ventures where others dare not go.",
        "Eyes that shimmer with the secrets of the cosmos, this cat is a celestial guide.",
        "A moonlit sage, this cat possesses ancient wisdom and insight.",
        "In the moon's reflection, this cat finds peace and tranquility.",
        "A mysterious silhouette, this cat blends seamlessly into the night's canvas.",
        "With a whisper of moonlight, this cat casts enchantments that bewitch the senses.",
        "A twilight wanderer, this cat explores the realms between light and darkness.",
        "Eyes like celestial beacons, this cat illuminates the night with its presence.",
        "A moonlit warrior, this cat's courage shines brightest under the lunar glow.",
        "In the moon's embrace, this cat finds solace and serenity.",
        "A phantom of the night, this cat vanishes into the shadows with grace and ease.",
        "With a moonlit aura, this cat radiates an ethereal beauty.",
        "A nocturnal dancer, this cat moves with elegance and poise under the moon's gentle light.",
        "Eyes that reflect the mysteries of the universe, this cat is a cosmic marvel.",
        "A moonlit sentinel, this cat stands guard over the night's secrets.",
        "A mysterious silhouette against the moon, this cat embodies the enigma of the night.",
        "With each leap, this cat defies gravity and glides through the moonlit sky.",
        "A conductor of nocturnal symphonies, this cat orchestrates melodies of moonlit magic.",
        "Eyes that hold the wisdom of ancient celestial beings, this cat is a timeless soul.",
        "A guardian of the night, this cat protects the world from the shadows that lurk.",
        "In the moon's radiance, this cat becomes a beacon of hope and tranquility.",
        "A shadowy figure cloaked in mystery, this cat is an enigma of the night.",
        "With each flick of its tail, this cat weaves moonlight into spells of enchantment.",
        "A nocturnal explorer, this cat delves into hidden realms under the moon's gentle glow.",
        "Eyes that sparkle like distant galaxies, this cat is a cosmic marvel.",
        "A lunar guardian, this cat watches over the world with unwavering devotion.",
        "In the moon's glow, this cat's true nature is revealed - a fearless warrior.",
        "A master of shadows, this cat moves silently through the night, undetected.",
        "With a gentle touch, this cat paints the world in shades of moonlit wonder.",
        "A moonstruck visionary, this cat perceives truths beyond mortal comprehension.",
        "A guardian of the night, this cat defends against the encroaching darkness.",
        "Eyes that hold the mysteries of the universe, this cat is a celestial enigma.",
        "A twilight dancer, this cat's movements are a graceful ballet in the moonlight.",
        "With each moonbeam, this cat's powers of transformation grow stronger.",
        "A seeker of nocturnal treasures, this cat embarks on daring quests beneath the moon's glow.",
        "Eyes that shimmer with the secrets of the cosmos, this cat is a celestial guide.",
        "A moonlit sage, this cat possesses ancient wisdom and profound insight.",
        "In the moon's reflection, this cat finds serenity and inner peace.",
        "A mysterious silhouette, this cat melds seamlessly into the night's tapestry.",
        "With a whisper of moonlight, this cat casts enchantments that captivate the senses.",
        "A twilight wanderer, this cat explores the realms between light and darkness.",
        "Eyes like celestial beacons, this cat illuminates the night with its presence.",
        "A moonlit warrior, this cat's bravery shines brightest under the lunar glow.",
        "In the moon's embrace, this cat finds solace and tranquility.",
        "A phantom of the night, this cat disappears into the shadows with grace and stealth.",
        "With a moonlit aura, this cat exudes an ethereal beauty.",
        "A nocturnal dancer, this cat moves with elegance and grace under the moon's gentle light.",
        "Eyes that reflect the mysteries of the universe, this cat is a cosmic marvel.",
        "A moonlit sentinel, this cat keeps watch over the night's secrets.",
        "A mysterious silhouette against the moon, this cat embodies the enigma of the night.",
        "With each leap, this cat defies gravity and glides through the moonlit sky.",
        "A conductor of nocturnal symphonies, this cat orchestrates melodies of moonlit magic.",
        "Eyes that hold the wisdom of ancient celestial beings, this cat is a timeless soul.",
        "A guardian of the night, this cat protects the world from the shadows that lurk.",
        "In the moon's radiance, this cat becomes a beacon of hope and tranquility.",
        "A shadowy figure cloaked in mystery, this cat is an enigma of the night.",
        "With each flick of its tail, this cat weaves moonlight into spells of enchantment.",
        "A nocturnal explorer, this cat delves into hidden realms under the moon's gentle glow.",
        "Eyes that sparkle like distant galaxies, this cat is a cosmic marvel.",
        "A lunar guardian, this cat watches over the world with unwavering devotion.",
        "In the moon's glow, this cat's true nature is revealed - a fearless warrior.",
        "A master of shadows, this cat moves silently through the night, undetected.",
        "With a gentle touch, this cat paints the world in shades of moonlit wonder.",
        "A moonstruck visionary, this cat perceives truths beyond mortal comprehension.",
        "A guardian of the night, this cat defends against the encroaching darkness.",
        "Eyes that hold the mysteries of the universe, this cat is a celestial enigma.",
        "A twilight dancer, this cat's movements are a graceful ballet in the moonlight.",
        "With each moonbeam, this cat's powers of transformation grow stronger.",
        "A seeker of nocturnal treasures, this cat embarks on daring quests beneath the moon's glow.",
        "Eyes that shimmer with the secrets of the cosmos, this cat is a celestial guide.",
        "A moonlit sage, this cat possesses ancient wisdom and profound insight.",
        "In the moon's reflection, this cat finds serenity and inner peace.",
        "A mysterious silhouette, this cat melds seamlessly into the night's tapestry.",
        "With a whisper of moonlight, this cat casts enchantments that captivate the senses.",
        "A twilight wanderer, this cat explores the realms between light and darkness.",
        "Eyes like celestial beacons, this cat illuminates the night with its presence.",
        "A moonlit warrior, this cat's bravery shines brightest under the lunar glow.",
        "In the moon's embrace, this cat finds solace and tranquility.",
        "A phantom of the night, this cat disappears into the shadows with grace and stealth.",
        "With a moonlit aura, this cat exudes an ethereal beauty.",
        "A nocturnal dancer, this cat moves with elegance and grace under the moon's gentle light.",
        "Eyes that reflect the mysteries of the universe, this cat is a cosmic marvel.",
        "A moonlit sentinel, this cat keeps watch over the night's secrets.",
        "A mysterious silhouette against the moon, this cat embodies the enigma of the night.",
        "With each leap, this cat defies gravity and glides through the moonlit sky.",
        "A conductor of nocturnal symphonies, this cat orchestrates melodies of moonlit magic.",
        "Eyes that hold the wisdom of ancient celestial beings, this cat is a timeless soul.",
        "A guardian of the night, this cat protects the world from the shadows that lurk.",
        "In the moon's radiance, this cat becomes a beacon of hope and tranquility.",
        "A shadowy figure cloaked in mystery, this cat is an enigma of the night.",
        "With each flick of its tail, this cat weaves moonlight into spells of enchantment.",
        "A nocturnal explorer, this cat delves into hidden realms under the moon's gentle glow.",
        "Eyes that sparkle like distant galaxies, this cat is a cosmic marvel.",
        "A lunar guardian, this cat watches over the world with unwavering devotion.",
        "In the moon's glow, this cat's true nature is revealed - a fearless warrior.",
        "A master of shadows, this cat moves silently through the night, undetected.",
        "With a gentle touch, this cat paints the world in shades of moonlit wonder.",
        "A moonstruck visionary, this cat perceives truths beyond mortal comprehension.",
        "A guardian of the night, this cat defends against the encroaching darkness.",
        "Eyes that hold the mysteries of the universe, this cat is a celestial enigma.",
        "A twilight dancer, this cat's movements are a graceful ballet in the moonlight.",
        "With each moonbeam, this cat's powers of transformation grow stronger.",
        "A seeker of nocturnal treasures, this cat embarks on daring quests beneath the moon's glow.",
        "Eyes that shimmer with the secrets of the cosmos, this cat is a celestial guide.",
        "A moonlit sage, this cat possesses ancient wisdom and profound insight.",
        "In the moon's reflection, this cat finds serenity and inner peace.",
        "A mysterious silhouette, this cat melds seamlessly into the night's tapestry.",
        "With a whisper of moonlight, this cat casts enchantments that captivate the senses.",
        "A twilight wanderer, this cat explores the realms between light and darkness.",
        "Eyes like celestial beacons, this cat illuminates the night with its presence.",
        "A moonlit warrior, this cat's bravery shines brightest under the lunar glow.",
        "In the moon's embrace, this cat finds solace and tranquility.",
        "A phantom of the night, this cat disappears into the shadows with grace and stealth.",
        "With a moonlit aura, this cat exudes an ethereal beauty.",
        "A nocturnal dancer, this cat moves with elegance and grace under the moon's gentle light.",
        "Eyes that reflect the mysteries of the universe, this cat is a cosmic marvel.",
        "A moonlit sentinel, this cat keeps watch over the night's secrets.",
        "A mysterious silhouette against the moon, this cat embodies the enigma of the night.",
        "With each leap, this cat defies gravity and glides through the moonlit sky.",
        "A conductor of nocturnal symphonies, this cat orchestrates melodies of moonlit magic.",
        "Eyes that hold the wisdom of ancient celestial beings, this cat is a timeless soul.",
        "A guardian of the night, this cat protects the world from the shadows that lurk.",
        "In the moon's radiance, this cat becomes a beacon of hope and tranquility.",
        "A shadowy figure cloaked in mystery, this cat is an enigma of the night.",
        "With each flick of its tail, this cat weaves moonlight into spells of enchantment.",
        "A nocturnal explorer, this cat delves into hidden realms under the moon's gentle glow.",
        "Eyes that sparkle like distant galaxies, this cat is a cosmic marvel.",
        "A lunar guardian, this cat watches over the world with unwavering devotion.",
        "In the moon's glow, this cat's true nature is revealed - a fearless warrior.",
        "A master of shadows, this cat moves silently through the night, undetected.",
        "With a gentle touch, this cat paints the world in shades of moonlit wonder.",
        "A moonstruck visionary, this cat perceives truths beyond mortal comprehension.",
        "A guardian of the night, this cat defends against the encroaching darkness.",
        "Eyes that hold the mysteries of the universe, this cat is a celestial enigma.",
        "A twilight dancer, this cat's movements are a graceful ballet in the moonlight.",
        "With each moonbeam, this cat's powers of transformation grow stronger.",
        "A seeker of nocturnal treasures, this cat embarks on daring quests beneath the moon's glow.",
        "Eyes that shimmer with the secrets of the cosmos, this cat is a celestial guide.",
        "A moonlit sage, this cat possesses ancient wisdom and profound insight.",
        "In the moon's reflection, this cat finds serenity and inner peace.",
        "A mysterious silhouette, this cat melds seamlessly into the night's tapestry.",
        "With a whisper of moonlight, this cat casts enchantments that captivate the senses.",
        "A twilight wanderer, this cat explores the realms between light and darkness.",
        "Eyes like celestial beacons, this cat illuminates the night with its presence.",
        "A moonlit warrior, this cat's bravery shines brightest under the lunar glow.",
        "In the moon's embrace, this cat finds solace and tranquility.",
        "A phantom of the night, this cat disappears into the shadows with grace and stealth.",
        "With a moonlit aura, this cat exudes an ethereal beauty.",
        "A nocturnal dancer, this cat moves with elegance and grace under the moon's gentle light.",
        "Eyes that reflect the mysteries of the universe, this cat is a cosmic marvel.",
        "A moonlit sentinel, this cat keeps watch over the night's secrets.",
        "A mysterious silhouette against the moon, this cat embodies the enigma of the night.",
        "With each leap, this cat defies gravity and glides through the moonlit sky.",
        "A conductor of nocturnal symphonies, this cat orchestrates melodies of moonlit magic.",
        "Eyes that hold the wisdom of ancient celestial beings, this cat is a timeless soul.",
        "A guardian of the night, this cat protects the world from the shadows that lurk.",
        "In the moon's radiance, this cat becomes a beacon of hope and tranquility.",
        "A shadowy figure cloaked in mystery, this cat is an enigma of the night.",
        "With each flick of its tail, this cat weaves moonlight into spells of enchantment.",
        "A nocturnal explorer, this cat delves into hidden realms under the moon's gentle glow.",
        "Eyes that sparkle like distant galaxies, this cat is a cosmic marvel.",
        "A lunar guardian, this cat watches over the world with unwavering devotion.",
        "In the moon's glow, this cat's true nature is revealed - a fearless warrior.",
        "A master of shadows, this cat moves silently through the night, undetected.",
        "With a gentle touch, this cat paints the world in shades of moonlit wonder.",
        "A moonstruck visionary, this cat perceives truths beyond mortal comprehension.",
        "A guardian of the night, this cat defends against the encroaching darkness.",
        "Eyes that hold the mysteries of the universe, this cat is a celestial enigma.",
        "A twilight dancer, this cat's movements are a graceful ballet in the moonlight.",
        "With each moonbeam, this cat's powers of transformation grow stronger.",
        "A seeker of nocturnal treasures, this cat embarks on daring quests beneath the moon's glow.",
        "Eyes that shimmer with the secrets of the cosmos, this cat is a celestial guide.",
        "A moonlit sage, this cat possesses ancient wisdom and profound insight.",
        "In the moon's reflection, this cat finds serenity and inner peace.",
        "A mysterious silhouette, this cat melds seamlessly into the night's tapestry.",
        "With a whisper of moonlight, this cat casts enchantments that captivate the senses.",
        "A twilight wanderer, this cat explores the realms between light and darkness.",
        "Eyes like celestial beacons, this cat illuminates the night with its presence.",
        "A moonlit warrior, this cat's bravery shines brightest under the lunar glow.",
        "In the moon's embrace, this cat finds solace and tranquility.",
        "A phantom of the night, this cat disappears into the shadows with grace and stealth.",
        "With a moonlit aura, this cat exudes an ethereal beauty.",
        "A nocturnal dancer, this cat moves with elegance and grace under the moon's gentle light.",
        "Eyes that reflect the mysteries of the universe, this cat is a cosmic marvel.",
        "A moonlit sentinel, this cat keeps watch over the night's secrets.",
        "A mysterious silhouette against the moon, this cat embodies the enigma of the night.",
        "With each leap, this cat defies gravity and glides through the moonlit sky.",
        "A conductor of nocturnal symphonies, this cat orchestrates melodies of moonlit magic.",
        "Eyes that hold the wisdom of ancient celestial beings, this cat is a timeless soul.",
        "A guardian of the night, this cat protects the world from the shadows that lurk.",
        "In the moon's radiance, this cat becomes a beacon of hope and tranquility.",
        "A shadowy figure cloaked in mystery, this cat is an enigma of the night.",
        "With each flick of its tail, this cat weaves moonlight into spells of enchantment.",
        "A nocturnal explorer, this cat delves into hidden realms under the moon's gentle glow.",
        "Eyes that sparkle like distant galaxies, this cat is a cosmic marvel.",
        "A lunar guardian, this cat watches over the world with unwavering devotion.",
        "In the moon's glow, this cat's true nature is revealed - a fearless warrior.",
        "A master of shadows, this cat moves silently through the night, undetected.",
        "With a gentle touch, this cat paints the world in shades of moonlit wonder.",
        "A moonstruck visionary, this cat perceives truths beyond mortal comprehension.",
        "A guardian of the night, this cat defends against the encroaching darkness.",
        "Eyes that hold the mysteries of the universe, this cat is a celestial enigma.",
        "A twilight dancer, this cat's movements are a graceful ballet in the moonlight.",
        "With each moonbeam, this cat's powers of transformation grow stronger.",
        "A seeker of nocturnal treasures, this cat embarks on daring quests beneath the moon's glow.",
        "Eyes that shimmer with the secrets of the cosmos, this cat is a celestial guide.",
        "A moonlit sage, this cat possesses ancient wisdom and profound insight.",
        "In the moon's reflection, this cat finds serenity and inner peace.",
        "A mysterious silhouette, this cat melds seamlessly into the night's tapestry.",
        "With a whisper of moonlight, this cat casts enchantments that captivate the senses.",
        "A twilight wanderer, this cat explores the realms between light and darkness.",
        "Eyes like celestial beacons, this cat illuminates the night with its presence.",
        "A moonlit warrior, this cat's bravery shines brightest under the lunar glow.",
        "In the moon's embrace, this cat finds solace and tranquility.",
        "A phantom of the night, this cat disappears into the shadows with grace and stealth.",
        "With a moonlit aura, this cat exudes an ethereal beauty.",
        "A nocturnal dancer, this cat moves with elegance and grace under the moon's gentle light.",
        "Eyes that reflect the mysteries of the universe, this cat is a cosmic marvel.",
        "A moonlit sentinel, this cat keeps watch over the night's secrets.",
        "A mysterious silhouette against the moon, this cat embodies the enigma of the night.",
        "With each leap, this cat defies gravity and glides through the moonlit sky.",
        "A conductor of nocturnal symphonies, this cat orchestrates melodies of moonlit magic.",
        "Eyes that hold the wisdom of ancient celestial beings, this cat is a timeless soul.",
        "A guardian of the night, this cat protects the world from the shadows that lurk.",
        "In the moon's radiance, this cat becomes a beacon of hope and tranquility.",
        "A shadowy figure cloaked in mystery, this cat is an enigma of the night.",
        "With each flick of its tail, this cat weaves moonlight into spells of enchantment.",
    ]

    for item in os.listdir(directory):
        if item.endswith(".jpeg") or item.endswith(".jpg") or item.endswith(".png"):
            item_info = {
                "name": f"#{str(counter).zfill(4)}",
                "descriptions": random.choice(descriptions_values),
                "image": item,
                "attributes": [
                    {
                        "trait_type": "color",
                        "value": random.choice(color_values),
                    },
                    {"trait_type": "eye", "value": random.choice(eye_values)},
                    {"trait_type": "ear", "value": random.choice(ear_values)},
                    {"trait_type": "face", "value": random.choice(face_values)},
                    {
                        "trait_type": "background",
                        "value": random.choice(background_values),
                    },
                    {"trait_type": "shirt", "value": random.choice(shirt_values)},
                ],
            }
            items.append(item_info)
            counter += 1

    # Create a dictionary to hold the items
    data = {"items": items}

    # Get the directory path and create a JSON file with the same name
    json_file_path = os.path.join(directory, "output.json")

    # Save the data to a JSON file
    with open(json_file_path, "w") as json_file:
        json.dump(data, json_file, indent=4)


# Specify the directory path where the items are located
directory_path = "/Users/macos/Desktop/cat-1/final-1"

# Call the function to get image names and save to JSON
get_image_names(directory_path)
